//
// Copyright 2026 Charles W. Rapp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
 * <h2>Event File System I/O Package</h2>
 *
 * <p>
 * The {@code org.efs.io} package provides the core I/O
 * capabilities for the Event File System (EFS). It defines an
 * in-memory (+ optional exhaust persistence) event store that
 * indexes events by both publish timestamp and row index,
 * enabling efficient event retrieval within specified time
 * and/or index intervals, supporting both historical event
 * retrieval and live event delivery.
 * </p>
 *
 * <h3>Core Components</h3>
 *
 * <dl>
 *   <dt>{@link org.efs.io.EfsFile}</dt>
 *   <dd>
 *     Central class for managing event storage and retrieval.
 *     {@code EfsFile} stores {@link org.efs.event.IEfsEvent}
 *     instances indexed by publish timestamp and monotonically
 *     increasing row index. Each row is unique by row index,
 *     while publish timestamps may be duplicated but are
 *     guaranteed to increase monotonically. The class is
 *     thread-safe and uses CQEngine for efficient indexed
 *     queries.
 *   </dd>
 *   <dt>{@link org.efs.io.EfsFileConnection}</dt>
 *   <dd>
 *     {@code EfsFile} access point for agents. Agents use this
 *     connection to add and retrieve events to and from the
 *     efs event file based on the
 *     {@link org.efs.io.EfsFile.AccessMode access mode} used to
 *     create the connection.
 *   </dd>
 *   <dt>{@link org.efs.io.EfsRow}</dt>
 *   <dd>
 *     Encapsulates a stored event along with its metadata:
 *     publish timestamp and unique row index. {@code EfsRow} is
 *     the unit of storage returned during event retrieval
 *     operations.
 *   </dd>
 *   <dt>{@link org.efs.io.EfsInterval}</dt>
 *   <dd>
 *     Defines a temporal or index-based interval for retrieving
 *     events. Supports flexible interval specification using
 *     fixed times, relative durations, or index offsets, with
 *     inclusive or exclusive endpoint boundaries.
 *   </dd>
 *   <dt>{@link org.efs.io.EfsIntervalEndpoint}</dt>
 *   <dd>
 *     Represents a single endpoint of an {@code EfsInterval}.
 *     Endpoints can be specified as fixed timestamps,
 *     time-relative offsets, or row index offsets.
 *   </dd>
 * </dl>
 *
 * <h3>Event Retrieval Pattern</h3>
 *
 * <p>
 * The package supports a flexible event retrieval model:
 * </p>
 *
 * <ul>
 *   <li>
 *     <strong>Historical Events:</strong> Retrieve events that
 *     have already been stored within a specified time interval
 *     or index range.
 *   </li>
 *   <li>
 *     <strong>Live Events:</strong> Subscribe to future events
 *     matching specified criteria and are published after the
 *     retrieval request is initiated.
 *   </li>
 *   <li>
 *     <strong>Hybrid Retrieval:</strong> Retrieve both
 *     historical events and subscribe to future events in a
 *     single request.
 *   </li>
 * </ul>
 *
 * <p>
 * Retrieval is controlled through
 * {@link org.efs.io.EfsFileConnection.Retrieval Retrieval} subscriptions
 * returned from
 * {@link org.efs.io.EfsFileConnection#retrieve(org.efs.io.EfsInterval, com.googlecode.cqengine.query.Query, java.util.function.Consumer, java.util.function.Consumer) EfsFile.retrieve}.
 * </p>
 *
 * <h3>Creating a Retrieval Query</h3>
 *
 * <p>
 * {@code EfsFile} stores {@code IEfsEvent}-implementing objects
 * in a cqengine {@code IndexCollection}.
 * {@code EfsFile.retrieve} access a user
 * {@link com.googlecode.cqengine.query.Query Query} which use
 * {@link com.googlecode.cqengine.attribute.Attribute Attribute}
 * to retrieve values from {@code IndexCollection} values.
 * <em>But there is a catch:</em>
 * </p>
 * <p style="background-color:#ffcccc;padding:5px;border: 2px solid darkred;">
 * {@code EfsFile} stores event within an
 * {@link org.efs.io.EfsRow EfsRow} and the row is stored in
 * {@code IndexCollection}.
 * </p>
 * <p>
 * This means that creating {@code Attribute} instances directly
 * from the stored event class will not work because the event
 * class is <em>not</em> stored directly in the index collection.
 * What is worse, providing a query based on such attributes
 * results in asynchronous retrieval failures.
 * </p>
 * <p>
 * The solution is to use event attributes generated by efs file.
 * These attributes can be accessed via
 * {@link org.efs.io.EfsFile#attribute(java.lang.String) EfsFile.attribute(String field)}
 * where {@code field} is the event field name. If the event has
 * a getter method {@code long getId()}, then the field name is
 * "id". Below sample code shows how to create a user query
 * for {@code UserLoginEvent}.
 * </p>
 * <p>
 * {@code EfsFile} generates cqengine attributes for event fields
 * based on the {@link org.efs.io.CQAttribute &#64;CQAttribute}
 * annotation. This annotation has three fields:
 * </p>
 * <ol>
 *   <li>
 *     {@link org.efs.io.CQAttribute#attribute() attribute}:
 *     defines
 *     {@link org.efs.io.CQAttributeType cqengine attribute type}.
 *     This includes: simple, simple (nullable), multi-value, and
 *     multi-value (nullable).
 *   </li>
 *   <li>
 *     {@code org.efs.io.CQAttribute#nullValues nullValues}: set
 *     to {@code true} if attribute type is
 *     {@link org.efs.io.CQAttributeType#MULTIVALUE_NULLABLE}
 *     where field returns an {@code Iterable} containing
 *     {@code null} values. Default setting is {@code false}.
 *     This field is ignored for all other attribute types.
 *   </li>
 *   <li>
 *     {@code org.efs.io.CQAttribute#index index} defines
 *     {@link org.efs.io.CQIndexType cqengine index type} applied
 *     to the attribute. Default setting is
 *     {@link org.efs.io.CQIndexType#NO_INDEX no index}.
 *   </li>
 * </ol>
 * <p>
 * See
 * <a href="https://github.com/npgall/cqengine?tab=readme-ov-file" target="_blank">cqengine GitHub project</a>
 * page for further explanation on attributes and indices.
 * </p>
 *
 * <h3>Usage Example</h3>
 *
 * <p>
 * Here is a typical usage pattern for adding events and retrieving them:
 * </p>
 *
 * <pre><code>import org.efs.event.EfsTopicKey;
 * import org.efs.dispatcher.IEfsAgent;
 * import org.efs.event.IEfsEvent;
 * import org.efs.io.EfsFile;
 * import org.efs.io.EfsFile.AccessMode;
 * import org.efs.io.EfsRow;
 * import org.efs.io.EfsInterval;
 * import org.efs.io.EfsTimeEndpoint;
 * import org.efs.io.EfsIntervalEndpoint.EndpointType;
 * import org.efs.io.EfsIntervalEndpoint.Clusivity;
 * import com.googlecode.cqengine.query.Query;
 * import static com.googlecode.cqengine.query.QueryFactory.startsWith;
 * import java.time.Instant;
 * import java.util.concurrent.atomic.AtomicInteger;
 *
 * // Define a custom event class implementing IEfsEvent
 * public final class UserLoginEvent implements IEfsEvent {
 *     private final String userId;
 *     private final String ipAddress;
 *     private final long timestamp;
 *
 *     public UserLoginEvent(String userId, String ipAddress, long timestamp) {
 *         this.userId = userId;
 *         this.ipAddress = ipAddress;
 *         this.timestamp = timestamp;
 *     }
 *
 *     // Getter methods for fields "userId", "ipAddress", and "timestamp".
 *     // Define cqengine attribute type and index type used for efs-generated attributes and indicies.
 *     // If there is no
 *     &#64;CqAttribute (attribute = CQAttributeType.SIMPLE, index = CQIndexType.HASH_INDEX)
 *     public String getUserId() { return userId; }
 *
 *     &#64;CqAttribute (attribute = CQAttributeType.SIMPLE, index = CQIndexType.RADIX_TREE_INDEX)
 *     public String getIpAddress() { return ipAddress; }
 *
 *     &#64;CqAttribute (attribute = CQAttributeType.SIMPLE, index = CQIndexType.NAVIGABLE_INDEX)
 *     public long getTimestamp() { return timestamp; }
 * }
 *
 * // Define an application agent implementing IEfsAgent for processing retrieved UserLoginEvent rows.
 * public final class AppAgent implements IEfsAgent {
 *     private final AtomicInteger eventCount = new AtomicInteger(0);
 *
 *     public void onUserLogin(final EfsRow&lt;UserLoginEvent&gt; row) {
 *         UserLoginEvent event = row.getEvent();
 *         System.out.println("Event at index " + row.getRowIndex() +
 *                            " published at " + row.getPublishTimestamp() +
 *                            ": User " + event.getUserId() +
 *                            " logged in from " + event.getIpAddress());
 *         eventCount.incrementAndGet();
 *     }
 *
 *     public void onDone(final RetrievalCompleteEvent&lt;UserLoginEvent&gt; event) {
 *         System.out.println("Retrieval complete. Total events: " + eventCount.get());
 *         System.out.println("Completion type: " + completionEvent.completionType());
 *     }
 * }
 *
 * // In your application:
 *
 * // 1. Create or open an EfsFile for a specific topic and event type
 * EfsTopicKey&lt;UserLoginEvent&gt; topicKey =
 *     new EfsTopicKey&lt;&gt;("user.login", UserLoginEvent.class);
 *
 * EfsFile&lt;UserLoginEvent&gt; eventFile =
 *     EfsFile.openEventFile(topicKey, "default-dispatcher");
 *
 * // 2. Open connection to file.
 * EfsFileConnection&lt;UserLoginEvent&gt; connection =
 *     eventFile.connect(AccessMode.READ_WRITE, agent);
 *
 * // 3. Add events to the file
 * AppAgent agent = new AppAgent();
 * Instant now = eventFile.instant();
 *
 * eventFile.add(new UserLoginEvent("user123", "192.168.1.100", System.currentTimeMillis()));
 * eventFile.add(new UserLoginEvent("user456", "10.0.0.50", System.currentTimeMillis()));
 *
 * // 4. Retrieve events using an interval and query condition
 * // Define an interval: all events from 1 hour ago to now (inclusive)
 * Instant oneHourAgo = now.minusSeconds(3600);
 * EfsInterval interval = new EfsInterval(
 *     new EfsTimeEndpoint(oneHourAgo, Clusivity.INCLUSIVE),
 *     new EfsTimeEndpoint(now, Clusivity.INCLUSIVE)
 * );
 * Attribute&lt;EfsRow&lt;UserLoginEvent&gt;, String&gt; ipaddrAttribute = (Attribute&lt;EfsRow&lt;UserLoginEvent&gt;, String&gt;) eventFile.attribute("ipAddress");
 * Query ipQuery = startsWith(ipaddrAttribute, "192.168.1");
 *
 * // 5. Process retrieved events with callbacks
 * try (var retrieval = eventFile.retrieve(interval,
 *                                         ipQuery,            // User logging in from local IP address.
 *                                         agent::onUserLogin, // Event callback: invoked for each matching event
 *                                         agent::onDone);     // Completion callback: invoked when retrieval is finished
 *     // Retrieval is now active and subscribed
 *     // New events published during the retrieval interval will be delivered
 * }</code></pre>
 *
 * <h3>Key Features</h3>
 *
 * <dl>
 *   <dt>Efficient Indexing</dt>
 *   <dd>
 *     Events are indexed by both publish timestamp (hash index)
 *     and row index (unique index), enabling fast queries on
 *     both dimensions.
 *   </dd>
 *   <dt>Flexible Intervals</dt>
 *   <dd>
 *     Intervals can be specified using fixed timestamps,
 *     durations relative to the latest event, or row index
 *     offsets, providing flexibility for various retrieval
 *     scenarios.
 *   </dd>
 *   <dt>Thread-Safe Operations</dt>
 *   <dd>
 *     {@code EfsFile} is annotated with {@code @ThreadSafe} and
 *     uses atomic operations and concurrent data structures to
 *     ensure safe concurrent access.
 *   </dd>
 *   <dt>Event Filtering</dt>
 *   <dd>
 *     Beyond interval filtering, events can be filtered using
 *     CQEngine queries on event properties, allowing
 *     fine-grained control over which events are retrieved.
 *   </dd>
 *   <dt>Live Subscription Support</dt>
 *   <dd>
 *     Retrieval requests can remain active to receive new events
 *     as they are published, enabling real-time event delivery
 *     patterns.
 *   </dd>
 *   <dt>Dispatcher Integration</dt>
 *   <dd>
 *     All event operations are coordinated through an
 *     {@link org.efs.dispatcher.EfsDispatcher}, ensuring
 *     thread-safe, ordered processing of events and retrieval
 *     requests.
 *   </dd>
 * </dl>
 *
 * <h3>Exception Handling</h3>
 *
 * <p>
 * The package defines clear exception semantics:
 * </p>
 *
 * <ul>
 *   <li>
 *     {@code NullPointerException} is thrown when required
 *     arguments are {@code null}.
 *   </li>
 *   <li>
 *    {@code IllegalArgumentException} is thrown for invalid
 *    arguments (e.g., invalid dispatcher names).
 *   </li>
 *   <li>
 *     {@code IllegalStateException} is thrown when operations
 *     are performed in invalid states (e.g., agent not
 *     registered with dispatcher)
 *   </li>
 * </ul>
 *
 * @see org.efs.io.EfsFile
 * @see org.efs.io.EfsFileConnection
 * @see org.efs.io.EfsRow
 * @see org.efs.event.IEfsEvent
 * @see org.efs.dispatcher.EfsDispatcher
 *
 * @author <a href="mailto:rapp@acm.org">Charles W. Rapp</a>
 * @since 0.7.1
 */

package org.efs.io;
